version: 2.1
orbs:
  node: circleci/go@1.5.0
jobs:
  build-and-test:
    executor:
      name: go/default
      tag: '1.15'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test:
          covermode: atomic
          failfast: true
          race: true
workflows:
    build-and-test:
      jobs:
        - build-and-test
