version: 2.1
jobs:
  build:
    docker:
      - image: cimg/go:1.13

    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            go test ./server/...

workflows:
    build:
      jobs:
        - build
