version: 2.1
jobs:

  build:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run:
          name: Run Database and Test
          command: |
            docker-compose up -d
workflows:
    build:
      jobs:
        - build
