version: 2.1
jobs:

  build:

    docker:

      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: core
          POSTGRES_DB: scheduler0_test
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD

      - image: cimg/go:1.13
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD

    steps:

      - checkout

      - run:
          name: Run tests
          command: |
            cd server
            go install
            go test ./...

workflows:
    build:
      jobs:
        - build
