version: 2.1
orbs:
  go: circleci/go@1.5.0
jobs:
  build:
    docker:
      - image: circleci/postgres:11-alpine-ram
        environment:
          POSTGRES_ADDRESS=localhost:5432
          POSTGRES_DATABASE=scheduler0_test
          POSTGRES_DB=scheduler0_test
          POSTGRES_USER=core
          POSTGRES_PASSWORD=localdev

    steps:
      - checkout
      - go/test:
        packages: ./server/...

workflows:
    build:
      jobs:
        - build
