version: 2.1
orbs:
  go: circleci/go@1.5.0
jobs:
  build-and-test:
    executor:
      name: go/default
      tag: '1.15'
    steps:
      - go/test:
        packages: server/...
workflows:
    build-and-test:
      jobs:
        - build-and-test
