version: 2.1
orbs:
  go: circleci/go@1.5.0
jobs:
  build-and-test:
    executor:
      name: go/default
      tag: '1.15'
    steps:
      - checkout:
          path: ~/cron-server/server
      - go/test:
          covermode: atomic
          failfast: true
          race: true
workflows:
    build-and-test:
      jobs:
        - build-and-test
