version: 2.1
jobs:
  build:
    docker:

#      - image: circleci/postgres:9.6.2-alpine
#        environment:
#          POSTGRES_USER: core
#          POSTGRES_DB: scheduler0_test

      - image: cimg/go:1.13

    steps:
      - checkout

      - run:
          name: Swtich to server
          command: |
            cd server

      - run:
          name: Install Go modules
          command: |
            go install

      - run:
          name: Run tests
          command: |
            go test ./...

workflows:
    build:
      jobs:
        - build
