version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
      - image: circleci/postgres:11-alpine-ram
        environment:
          POSTGRES_ADDRESS=localhost:5432
          POSTGRES_DATABASE=scheduler0_test
          POSTGRES_DB=scheduler0_test
          POSTGRES_USER=core
          POSTGRES_PASSWORD=localdev
  build-and-test:
    steps:
      - go/test:
        packages: ./server/...
workflows:
    build-and-test:
      jobs:
        - build
        - build-and-test
