version: 2.1
jobs:

  build:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run:
          name: Run Database
          command: |
            docker-compose up -d postgres
      - run:
          name: Run Test
          command: |
            docker-compose up -d server
      - run:
          name: Test in Container
          command: |
            docker exec -it project_server_1 go test ./... -cover -v
workflows:
    build:
      jobs:
        - build
