version: 2.1
orbs:
  go: circleci/go@1.5.0
jobs:
  build:
    executor:
      name: go/default
      tag: '1.15'
    docker:
      - image: circleci/postgres:11-alpine-ram
        environment:
          POSTGRES_ADDRESS=localhost:5432
          POSTGRES_DATABASE=scheduler0_test
          POSTGRES_DB=scheduler0_test
          POSTGRES_USER=core
          POSTGRES_PASSWORD=localdev

    working_directory: ~/scheduler0

    steps:
      - go/test


workflows:
    build:
      jobs:
        - build
